stages:
  - lint
  - test

prettier:
  image: node:8.15-alpine
  stage: lint
  before_script:
    - npm install
  script:
    - npm run format-test
  tags:
    - privileged

eslint:
  image: node:8.15-alpine
  stage: lint
  before_script:
    - npm install
  script:
    - npm run lint
  tags:
    - privileged

test:
  image: node:8.15-alpine
  stage: test
  before_script:
    - npm install
    - npm run build
  script:
    - npm run test
  tags:
    - privileged
